Marketing/Controllers/ReportController.cs
using Marketing.Helper;
using Marketing.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace Marketing.Controllers
{
    public class ReportController : Controller
    {
        private string serverpath = "~/Reports/";

        public ActionResult Index(string name, string category)
        {
            var hreport = new HReport(Server, serverpath);
            var r = new ReportViewModel();
            r.Name = name;
            r.Category = category;
            r.Reports = hreport.List(r.Category);
            return View(r);
        }

        public ActionResult ExportPDF(string category, string filename, string param)
        {
            try
            {
                var server = WebConfigurationManager.AppSettings["reportserver"];
                var database = WebConfigurationManager.AppSettings["reportdatabase"];
                var user = WebConfigurationManager.AppSettings["reportuser"];
                var pass = WebConfigurationManager.AppSettings["reportpass"];

                var hreport = new HReport(Server, serverpath);
                var parameters = JsonConvert.DeserializeObject<List<HReportParameter>>(param);
                var stream = hreport.ExportPDF(server, database, user, pass, category, filename, parameters);

                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();
                return File(stream, "application/pdf");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

Marketing/Views/Shared/_Footer.cshtml
<div id="loading" class="hide">
    <div class="lds-spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
</div>

<script>
        document.addEventListener("DOMContentLoaded", function (event) {
            initmahas();
        });
</script>

Marketing/Views/Shared/_Header.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>@ViewBag.Title - @Marketing.Helper.ConfigModel.AppName</title>

<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
<link href="~/Themes/assets/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/Themes/assets/css/colors.min.css" rel="stylesheet" />
<link href="~/Themes/assets/css/components.min.css" rel="stylesheet" />
<link href="~/Themes/assets/css/core.min.css" rel="stylesheet" />
<link href="~/Themes/assets/css/icons/icomoon/styles.css" rel="stylesheet" />
<link href="~/Themes/assets/css/icons/fontawesome/styles.min.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />

<script src="~/Themes/assets/js/core/libraries/jquery.min.js"></script>
<script src="~/Themes/assets/js/core/libraries/bootstrap.min.js"></script>
<script src="~/Themes/assets/js/core/app.min.js"></script>
<script src="~/Themes/assets/js/plugins/forms/selects/select2.min.js"></script>
<script src="~/Themes/assets/js/plugins/cleave.min.js"></script>

<script src="~/Scripts/mahas.js"></script>

Marketing/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("_Header")
    <style>

        .app-name {
            font-size: 18px;
            font-weight: bolder;
            letter-spacing: 3px;
            text-align: center;
        }

        .navbar-brand {
            width: 100%;
            padding: 13px;
        }
    </style>
</head>

@{
    var sidebar = Request.Cookies["sidebar"] == null ? false : bool.Parse(Request.Cookies["sidebar"].Value);
}

<body class="@(sidebar ? "" : "sidebar-xs")">
    <div class="navbar navbar-inverse">

        <div class="navbar-header">
            <a class="navbar-brand text-center" href="@Url.Action("Index", "Home")">
                <span class="app-name ">MARKETING</span>
                @*<img src="~/Themes/assets/images/logo_light.png" />*@
            </a>
            <ul class="nav navbar-nav pull-right visible-xs-block">
                <li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
                <li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
            </ul>
        </div>

        <div class="navbar-collapse collapse" id="navbar-mobile">
            @if (User.Identity.IsAuthenticated)
            {
                <ul class="nav navbar-nav">
                    <li><a class="sidebar-control sidebar-main-toggle hidden-xs" onclick="sidebartoggleclick()"><i class="icon-paragraph-justify3"></i></a></li>
                </ul>
            }

            @Html.Partial("_LoginPartial")
        </div>
    </div>

    <div class="page-container">
        <div class="page-content">

            @if (User.Identity.IsAuthenticated)
            {
                @Html.Partial("_Menu")
            }

            <div class="content-wrapper">
                <div class="page-header page-header-default">
                    <div class="breadcrumb-line">
                        <ul class="breadcrumb">
                            <li><a href="@Url.Action("Index", "Home")"><i class="icon-home2 position-left"></i> Home</a></li>
                            @if (ViewBag.breadcrumb != null)
                            {
                                foreach (var i in (List<SelectListItem>)ViewBag.breadcrumb)
                                {
                                    if (i.Value == "active")
                                    {
                                        <li class="active">@i.Text</li>
                                    }
                                    else
                                    {
                                        <li><a href="@i.Value">@i.Text</a></li>
                                    }
                                }
                            }
                        </ul>
                    </div>
                </div>
                <div class="content">

                    @RenderBody()

                    <div class="footer text-muted">
                        © 2020. @Marketing.Helper.ConfigModel.AppName by <a href="https://www.sanatasystem.net/" target="_blank">Sanata System</a>
                    </div>
                </div>
            </div>

        </div>
    </div>

    @Html.Partial("_Footer")
    @RenderSection("scripts", required: false)
</body>
</html>

Marketing/Views/Shared/_Menu.cshtml
@using Microsoft.AspNet.Identity
<div class="sidebar sidebar-main">
    <div class="sidebar-content">
        <div class="sidebar-category sidebar-category-visible">
            <div class="category-content no-padding">
                <ul class="navigation navigation-main navigation-accordion">

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="navigation-header"><span>Menu</span> <i class="icon-menu" title="Menu"></i></li>
                        <li><a href="@Url.Action("Index", "Home")"><i class="icon-home"></i> <span>Home</span></a></li>
                        <li>
                            <a href="#" class="has-ul"><i class="icon-database-menu"></i> <span>Setup</span></a>
                            <ul class="hidden-ul">
                                <li><a href="@Url.Action("Index", "PerusahaanKerjasama")">Perusahaan Kerjasama</a></li>
                                <li><a href="@Url.Action("Index", "Departemen")">Departemen</a></li>
                                <li><a href="@Url.Action("Index", "JenisPasien")">Jenis Pasien</a></li>
                                <li><a href="@Url.Action("Index", "TypeAsuransi")">Type Asuransi</a></li>
                                <li><a href="@Url.Action("Index", "NamaAsuransi")">Nama Asuransi</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="has-ul"><i class="icon-collaboration"></i> <span>Kerjasama</span></a>
                            <ul class="hidden-ul">
                                <li><a href="@Url.Action("Index", "SetupAnggotaKerjasama")">Setup Anggota Kerjasama</a></li>
                                <li><a href="@Url.Action("Index", "SetupKontrakKerjasama")">Setup Kontrak Kerjasama</a></li>
                                <li><a href="@Url.Action("Index", "SetupTarifKerjasamaModel")">Setup Tarif Kerjasama</a></li>
                                <li><a href="@Url.Action("Index", "SetupKontrakMCU")">Setup Kontrak MCU</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="has-ul"><i class="icon-printer4"></i> <span>Report</span></a>
                            <ul class="hidden-ul">
                                <li><a href="@Url.Action("Index", "Report", new { name = "Laporan Rekap Marketing", category = "RekapMarketing"})">Laporan Rekap Marketing</a></li>
                                <li><a href="@Url.Action("Index", "Report", new { name = "Laporan Akumulasi Marketing", category = "AkumulasiMarketing"})">Laporan Akumulasi Marketing</a></li>
                            </ul>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</div>